name: BuildArtifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Jimver/cuda-toolkit@v0.2.8

    - name: Bootstrap vcpkg
      run: ./bootstrap-vcpkg.bat

    - name: Build artifacts
      # Build your program with the given configuration
      run: ./iconic-install-dependencies.bat
    
    - name: Export artifacts
      run: ./iconic-export-dependencies.bat

