name: BuildArtifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      max-parallel: 2
      matrix:
        config:
          # - os: ubuntu-latest
          - os: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        path: installed
        key: ${{ matrix.config.os }}-vcpkg-install
        
    - name: Configure Pagefile (Windows)
      if: ${{ matrix.config.os == 'windows-latest' }}
      uses: al-cheb/configure-pagefile-action@v1.3
      with:
        minimum-size: 10GB
        maximum-size: 12GB

    - name: Bootstrap vcpkg (Windows)
      if: ${{ matrix.config.os == 'windows-latest' }}
      run: ./bootstrap-vcpkg.bat

    - name: Build artifacts (Windows)
      if: ${{ matrix.config.os == 'windows-latest' }}
      run: ./iconic-install-dependencies.bat
    
    - name: Export artifacts (Windows)
      if: ${{ matrix.config.os == 'windows-latest' }}
      run: ./iconic-export-dependencies.bat
      
    - name: Setup swap (Ubunut)
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
      
    - name: Bootstrap vcpkg (Ubunut)
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: ./bootstrap-vcpkg.sh

    - name: Build artifacts (Ubunut)
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: ./iconic-install-dependencies.sh
    
    - name: Export artifacts (Ubunut)
      if: ${{ matrix.config.os == 'ubuntu-latest' }}
      run: ./iconic-export-dependencies.sh

