name: Test Release

on:
  push:
    branches: [ "master" ]

jobs:
  generate_assets:
    name: Gelease assets
    runs-on: ${{ matrix.config.os }} # we run many different builds
    strategy:
      # just an example matrix
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      # checkout of cource
      - name: Checkout code
        uses: actions/checkout@v3
      # ... whatever build and packaging steps you need here
      - name: Zip assets
        # uses: softprops/action-gh-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: zip test.zip test.bat
      # and finally do an upload!
      - name: Upload atrifacts
        uses: actions/upload-artifact@v3
        with:
          name: iconic-deps-${{ matrix.config.os }}.zip
          path: test.zip

  create_release:
    name: Create release
    needs: generate_assets
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - name: List artifacts
        run: pwd && ls -l ./artifacts
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            artifacts/*.zip
            artifacts/iconic-deps-ubuntu-latest.zip
            artifacts/iconic-deps-macos-latest.zip
